// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckContainerServiceRunning() {
    return $Call.ByID(2356871175);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartContainerService() {
    return $Call.ByID(1907780128);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopContainerService() {
    return $Call.ByID(860549216);
}
