// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CheckContainerServiceRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2356871175);
}

export function StartContainerService(): $CancellablePromise<void> {
    return $Call.ByID(1907780128);
}

export function StopContainerService(): $CancellablePromise<void> {
    return $Call.ByID(860549216);
}
