// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function ListImages(): $CancellablePromise<string> {
    return $Call.ByID(4186020358);
}

export function PullImage(imageName: string): $CancellablePromise<string> {
    return $Call.ByID(40965272, imageName);
}
