// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Image {
    "size": string;
    "digest": string;
    "mediaType": string;
    "host": string;
    "imageName": string;
    "tag": string;
    "created": string;

    /** Creates a new Image instance. */
    constructor($$source: Partial<Image> = {}) {
        if (!("size" in $$source)) {
            this["size"] = "";
        }
        if (!("digest" in $$source)) {
            this["digest"] = "";
        }
        if (!("mediaType" in $$source)) {
            this["mediaType"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("imageName" in $$source)) {
            this["imageName"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Image instance from a string or object.
     */
    static createFrom($$source: any = {}): Image {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Image($$parsedSource as Partial<Image>);
    }
}

export class ImageV2 {
    "name": string;
    "tag": string;
    "imageId": string;
    "architecture": string;
    "size": string;
    "created": string;

    /** Creates a new ImageV2 instance. */
    constructor($$source: Partial<ImageV2> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("imageId" in $$source)) {
            this["imageId"] = "";
        }
        if (!("architecture" in $$source)) {
            this["architecture"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageV2 instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageV2 {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageV2($$parsedSource as Partial<ImageV2>);
    }
}
